// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Y0VuYA1LRCfd0JYzdnaru0pEd93DhlY',
    appId: '1:679426021364:web:439ea7af7eab94a5c2cba1',
    messagingSenderId: '679426021364',
    projectId: 'lab11problem3',
    authDomain: 'lab11problem3.firebaseapp.com',
    storageBucket: 'lab11problem3.firebasestorage.app',
    measurementId: 'G-S67J66HLF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1PaBbi5ULbmbTLt0NrAy6qHF0UGjZ42Y',
    appId: '1:679426021364:android:68b0d4c3db195189c2cba1',
    messagingSenderId: '679426021364',
    projectId: 'lab11problem3',
    storageBucket: 'lab11problem3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdtz39RwGnyzaFNERj7Bxrq6mJlK67-2M',
    appId: '1:679426021364:ios:b9378567a2f02d23c2cba1',
    messagingSenderId: '679426021364',
    projectId: 'lab11problem3',
    storageBucket: 'lab11problem3.firebasestorage.app',
    iosBundleId: 'com.example.teepakornbodinWidgetsExercises',
  );
}
